development: &default
  adapter: postgresql
  encoding: unicode
  database: wizz_vis_development
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "app_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", 'app_password') %>
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>

test:
  <<: *default
  database: wizz_vis_test

production:
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  url:  <%= ENV.fetch("DATABASE_URL") %>
